### ISSUE TITLE
lean-default on sub-schema

### ISSUE THREAD

**Issue by floqast-tim** [DouglasGabr/mongoose-lean-defaults#26]
**Describe the bug**  
I was not able to get this plugin to work with a sub-schema. I attached the plugin to both the child schema, and then I attached to the parent and either way, the child schema did not come back with defaults set.

**To Reproduce**  

1. Create a Schema
2. Create sub-schema
3. Attach sub-schema to schema with defaults turned on, see below for example

`const mongooseLeanDefaults = require('mongoose-lean-defaults').default;`
`
const subSchema = new mongoose.Schema({
    subSchemaField: {
        subField1: {
            type: Boolean,
            default: false
        }
    }
})
`
`
const schema = new mongoose.Schema({
    schemaField: { 
        type: subSchema,
        defaults: {}
    }
}
`
`schema.plugin(mongooseLeanDefaults)`

**Expected behavior**  
When using schema.findOne.lean({ defaults: true }) I expected to get an object that looks like this.

`
{
    field: {
        subSchemaField: {
             subField1: false
        }
    }
}
`

However, subSchemaField comes back as undefined.

**Additional context**  
Mongoose version:  4.13.12
Node version: 14.15.4

**Comment by DouglasGabr** [comment]
Hi @floqast-tim. Sorry for the late reply,

1. double check your `schemaField` definition, since it is `{ type: subSchema, defaults: {} }`. Notice that you must use `default` and not `defaults` for it to work.
2. the library is only tested in mongoose>=5, so it might be something to do with the mongoose version. I've tested your example (replacing `defaults` with `default` first) and it worked as expected
