### ISSUE TITLE
Breaking change makes v2.1.1 incompatible with Mongoose v5, but still claims compatibility

### ISSUE THREAD

**Issue by carrolp** [DouglasGabr/mongoose-lean-defaults#27]
**Describe the bug**  

[This change](https://github.com/DouglasGabr/mongoose-lean-defaults/blob/2.1.1/src/index.ts#L140) introduces a dependency on `mongoose.Schema.Types.Subdocument`, but `Subdocument` is not added to `mongoose.Schema.Types` until Mongoose v6.  But `mongoose-lean-defaults` still states that its [peerDependency is mongoose >=5](https://github.com/DouglasGabr/mongoose-lean-defaults/blob/2.1.1/package.json#L32).

As a result, when used with mongoose v5, an error like this will occur:
```
"err":{"message":"Right-hand side of 'instanceof' is not an object","name":"TypeError","stack":"TypeError: Right-hand side of 'instanceof' is not an object\n    at getDefault ([MYPROJECT]/node_modules/mongoose-lean-defaults/index.js:140:25)....
```

Mongoose 5.13.14: https://github.com/Automattic/mongoose/blob/5.13.14/lib/schema/index.js (no Subdocument)
Mongoose 6.0.0: https://github.com/Automattic/mongoose/blob/6.0.0/lib/schema/index.js#L16 (has Subdocument)

If the dependency on `Subdocument` being defined is _necessary_, then I would think the peerDependency needs to be updated to `mongoose >=6`.  As that would be a breaking change (no longer compatible with v5), the `mongoose-leand-defaults` version should be bumped to 3.0.0 instead of 2.1.x.

We are updating our project to explicitly depend on `mongoose-lean-defaults` at version `2.1.0` (not `^2.1.0`) to avoid this breakage for now.

**To Reproduce**  

1. Use `mongoose-lean-defaults` with a project using Mongoose v5

**Expected behavior**  
`mongoose-lean-defaults` 2.x should continue to support Mongoose v5

**Additional context**  
Mongoose version:  5.13.14
Node version: 14, 16

**Comment by DouglasGabr** [comment]
@carrolp Thanks for reporting this issue.
I'll mark `v2.1.1` as deprecated because it introduces this unexpected breaking change.
I'll double check if there is some way to keep the same logic without relying on `mongoose.Schema.Types.Subdocument`.
- If so, I'll release `v2.1.2` with that implemented, and introduce automated tests with `mongoose@5`.
- If not, I'll release `v3.0.0` with the current code and bump `mongoose` peer dependency.

Any help is appreciated, if you want to contribute with a pull request.
